version: '3.8'

services:
  api:
    image: expense-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      - JwtSettings__Key=${JWTSETTINGS__KEY}
      - JwtSettings__Issuer=${JWTSETTINGS__ISSUER}
      - JwtSettings__Audience=${JWTSETTINGS__AUDIENCE}
      - Cloudinary__CloudName=${CLOUDINARY__CLOUDNAME}
      - Cloudinary__ApiKey=${CLOUDINARY__APIKEY}
      - Cloudinary__ApiSecret=${CLOUDINARY__APISECRET}
    depends_on:
      - db
    networks:
      - expense-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge

volumes:
  db-data:
