name: Build and deploy Expense.API to MonsterASP

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore API project
        run: dotnet restore .\Expense.API\Expense.API.csproj

      - name: Build API project
        run: dotnet build .\Expense.API\Expense.API.csproj --configuration Release --no-restore

      - name: Publish API project
        run: dotnet publish .\Expense.API\Expense.API.csproj --configuration Release --no-build --output .\publish --runtime win-x86

      - name: Deploy to MonsterASP via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.2.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: '\publish\'
